version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: linkedin_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: linkedin_jobs
    ports:
      - "5432:5432"
    networks:
      - linkedin_net

  linkedin_agent:
    build: .
    container_name: linkedin_agent
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=linkedin_jobs
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - MODEL_NAME=llama3
      - OLLAMA_URL=http://host.docker.internal:11434/api/generate   # ðŸ‘ˆ ici
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    command: ["python", "main.py"]
    networks:
      - linkedin_net
    # ðŸ”¥ permet d'accÃ©der Ã  Internet depuis le conteneur
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  linkedin_net:
    driver: bridge
